services:
  postgres:
    image: postgres:16
    container_name: biogenom-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGPORT: ${POSTGRES_PORT}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
      
  biogenom-api:
    build: .
    container_name: biogenom-api
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ConnectionStrings__BiogenomTestDb: ${CONNECTION_STRING}
    ports:
      - "5031:8080"

volumes:
  pgdata:
